## Matrices

Matrices are very common in transportation.  Two commont types of matrix data are: 

trip tables - matrices showing the number of trips between each zone pair

skims - matrices showing the travel time and cost between each zone pair


In [1]:
# you can represent matrices in python as two dimensional lists
m = [[1,2,3],[4,5,6],[7,8,9]]
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
# change the values by referring to the appropriate indices
m[0][0] = -1
m[1][2] = 999
m

[[-1, 2, 3], [4, 5, 999], [7, 8, 9]]

### Numpy matrices

This is fine, but can be slow if you're working with big matrices.  For those, it is nice to use numpy, which operates way faster.  Their quickstart tutorial offers a good intro: 

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In [3]:
import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# change the values by referring to the appropriate indices
m[0][0] = -1
m[1][2] = 999
m

array([[ -1,   2,   3],
       [  4,   5, 999],
       [  7,   8,   9]])

In [5]:
# Since an array is an object, it comes with some extra data 
m.shape

(3, 3)

In [6]:
# and some methods
m.max()

999

In [8]:
m.min()

-1



### OMX for matrix i/o

For saving groups of matrices to disk, OMX is a useful package.  Intro is here: 

https://github.com/osPlanning/omx/wiki

Python API is here: 

https://github.com/osPlanning/omx-python

Note that we sometimes want row and column indices that are non-sequential integers--the label of the TAZ rather than just a number 1 through N.  I've put an example matrix in the data folder for this lesson.  If you want to look at the contents, you can install the viewer, available on the wiki.  


### Homework

The example is a skim matrix showing different components of travel time between each TAZ pair.  The IVT matrix is for in-vehicle time (as opposed to walking and waiting time which are out-of-vehicle).  Notice that the values on the diagonal are all zeros.  This is the sort of thing that can cause divide by zero errors later on.  Your job is to read the matrix in, replace the zeros on the diagonals with ones, and save the matrix again.  

To do this, you will need to install the OMX package and review their quick start sample code to see what to do.  This is good practice in figuring stuff out from the types of resources that may be avaiable, and you should have the skills at this point in the course to do so.


In [37]:
import openmatrix as omx
import numpy as np


print('/Users/zhengjing/Documents/ce599-s17 gina/19-Materix and Network Data/data/example.omx')
myfile = omx.open_file('data/example.omx')

print ('Shape:', myfile.shape())                  
print ('Number of tables:', len(myfile))         
print ('Table names:', myfile.list_matrices()) 


/Users/zhengjing/Documents/ce599-s17 gina/19-Materix and Network Data/data/example.omx
Shape: (485, 485)
Number of tables: 8
Table names: ['FARE', 'IVT', 'IVTBUS', 'IVTRAIL', 'IVTTRAM', 'OWT', 'TRANSFERS', 'TWT']


In [38]:
IVT=myfile['IVT']
IVT=np.array(IVT)
IVT

array([[  0.00000000e+00,   4.65000000e+00,   1.02632127e+01, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       [  2.96974854e+01,   0.00000000e+00,   5.36321275e+00, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       [  2.32596530e+01,   2.83596530e+01,   0.00000000e+00, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       ..., 
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          0.00000000e+00,   4.26666667e+00,   9.16666667e+00],
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          3.02666667e+01,   0.00000000e+00,   4.40000000e+00],
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          2.51666667e+01,   2.94333333e+01,   0.00000000e+00]])

In [39]:
len (IVT)

485

In [40]:
i=0
j=0

while i <= len(IVT) -1: 
    IVT[i,i]=1
    i=i+1
    j=j+1

In [41]:
IVT[0,0]

1.0

In [42]:
IVT [484,484]

1.0

In [43]:
IVT

array([[  1.00000000e+00,   4.65000000e+00,   1.02632127e+01, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       [  2.96974854e+01,   1.00000000e+00,   5.36321275e+00, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       [  2.32596530e+01,   2.83596530e+01,   1.00000000e+00, ...,
          9.99999000e+05,   9.99999000e+05,   9.99999000e+05],
       ..., 
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          1.00000000e+00,   4.26666667e+00,   9.16666667e+00],
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          3.02666667e+01,   1.00000000e+00,   4.40000000e+00],
       [  9.99999000e+05,   9.99999000e+05,   9.99999000e+05, ...,
          2.51666667e+01,   2.94333333e+01,   1.00000000e+00]])

In [49]:
outfile=omx.open_file('/Users/zhengjing/Documents/ce599-s17 gina/19-Materix and Network Data/data/output.omx')

OSError: ``/Users/zhengjing/Documents/ce599-s17 gina/19-Materix and Network Data/data/output.omx`` does not exist

In [ ]:
outfile['IVT']=IVT